# -*- coding: utf-8 -*-
"""Hanna.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1U9KN_dGBejycQLsJwZeqhhlX1SPcNITa

## TESTE PROGRAMA AUXILIO CONFECÇÃO MINUTAS DE SENTENÇA
"""

perguntas = list()
numero_perguntas = int(input("quantas perguntas?"))

for i in range(numero_perguntas):
  perguntas.append(input(f"digite a pergunta numero {i+1} :" ))

print(perguntas[0],perguntas[1])



CABECALHO = "No intuito de comprovar a qualidade de segurado especial pelo tempo de carência necessário para a concessão do benefício pretendido, a parte autora apresentou os seguintes documentos:"

indagacao = input("há certidão de casamento com indicação da profissão de trabalhador(a) rural?")
indagacao2 = input("há declaração de PRONAF contemporânea ao período que se pretende comprovar?")
indagacao3 = input("há notas fiscais de aquisição de produtos agrícolas contemporânea ao período que se pretende comprovar?")
indagacao4 = input ("há consulta ao DATAPREV com informação de recebimento de benefício previdenciário na qualidade de segurado especial?")
indagacao5 = input("A prova oral produzida se mostrou suficiente para corroborar a prova documental, eis que as testemunhas apresentaram depoimento coerente e harmônico com a alegação de que a parte autora exerce atividade rural, em regime familiar, para fins de subsistência.")

print(CABECALHO)

print(CABECALHO)
NUMERODESIMS_=0
if indagacao=="sim":
  print("a) certidão de casamento com indicação da profissão de trabalhador(a) rural;")
  NUMERODESIMS_=NUMERODESIMS_+1

if indagacao2=="sim":
  print("b) declaração de PRONAF contemporâneas ao período que se pretende comprovar;")
  NUMERODESIMS_=NUMERODESIMS_+1

if indagacao3=="sim":
  print("c) notas fiscais de aquisição de produtos agrícolas contemporânea ao período que se pretende comprovar;")
  NUMERODESIMS_=NUMERODESIMS_+1

if indagacao4=="sim":
  print("d) consulta ao DATAPREV com informação de recebimento de benefício previdenciário na qualidade de segurado especial;")
  NUMERODESIMS_=NUMERODESIMS_+1

if NUMERODESIMS_ > 3:
  print("Os documentos acima elencados servem como prova material do exercício de atividade rural na qualidade de segurado especial.")
  print("Por seu turno, a prova oral produzida se mostrou suficiente para corroborar a prova documental, eis que as testemunhas apresentaram depoimento coerente e harmônico com a alegação de que a parte autora exerceu atividade rural, em regime familiar, para fins de subsistência.")
  print("Assim, a parte autora comprovou ter cumprido os requisitos dispostos na legislação de regência para a concessão da aposentadoria por idade na qualidade de segurado especial do Regime Geral de Previdência Social - RGPS, razão pela qual o pedido merece procedência.")

else:
  print("Os documentos acima elencados não são suficientes para indiciar o exercício de atividade rural na qualidade de segurado especial.\nPor seu turno, a prova oral produzida embora coerente, conforme Súmula n. 149 do Superior Tribunal de Justiça, tem que estar sustentada em prova material, o que não ocorreu no caso dos autos.\nAssim, a parte autora não comprovou ter cumprido os requisitos dispostos na legislação de regência para a concessão da aposentadoria por idade na qualidade de segurado especial do Regime Geral de Previdência Social - RGPS, razão pela qual o pedido não merece acolhimento.")